import { CardData } from "./types";
import {
    User, Shield, MessageCircle, Home, Sparkles, Activity, Users, Eye, Compass, Trophy, Star, Cloud,
    Sun, Moon, Flame, Brain, Sprout, Heart, Hourglass, Zap, Wind
} from "lucide-react";

export const houses: CardData[] = [
    {
        id: "h1",
        icon: User,
        type: "House",
        name: "1st House",
        title: "Self & Identity",
        description: "Tests how you see yourself, your confidence, and how you initiate actions in life.",
        detailedDescription: "This house explores your sense of identity, self-belief, and overall presence. It measures how confidently you approach new situations, how you define yourself internally, and the way you project your personality outward. High scores show strong agency; lower scores point toward uncertainty or self-questioning.",
        questions: [
            { id: "h1-q1", text: "I often struggle to assert my true personality in new groups." },
            { id: "h1-q2", text: "I feel confident in my ability to start new projects alone." },
            { id: "h1-q3", text: "My physical appearance significantly impacts my self-worth." },
        ],
        aiPrompt: "Focus on self-assertion, physical vitality, and the ability to initiate action. Ask about how they handle being the center of attention, their relationship with their physical body, and their independence.",
    },
    {
        id: "h2",
        icon: Shield,
        type: "House",
        name: "2nd House",
        title: "Values & Security",
        description: "Tests your relationship with security, stability, money, and the core values that guide your choices.",
        detailedDescription: "This house measures how you relate to material comfort, personal values, and emotional safety. It examines your need for stability, your attitude toward money, and how secure you feel within yourself. Dominance here suggests strong grounding; lower expression hints at instability or unclear priorities.",
        questions: [
            { id: "h2-q1", text: "Financial stability is more important to me than taking risks." },
            { id: "h2-q2", text: "I often compromise my values to please others." },
            { id: "h2-q3", text: "I feel secure in my ability to provide for myself." },
        ],
        aiPrompt: "Focus on material security, self-worth related to resources, and personal values. Ask about their spending habits, their need for stability, and how they define their own value.",
    },
    {
        id: "h3",
        icon: MessageCircle,
        type: "House",
        name: "3rd House",
        title: "Expression & Courage",
        description: "Tests your communication style, social boldness, and willingness to try new or challenging experiences.",
        detailedDescription: "This house evaluates how openly you express yourself, how you handle social interactions, and your appetite for risk or novelty. It reflects your ability to articulate ideas, stand up for yourself, and engage with the world. A strong score shows initiative; a low one suggests hesitation or self-censorship.",
        questions: [
            { id: "h3-q1", text: "I find it easy to express my controversial opinions." },
            { id: "h3-q2", text: "I enjoy learning new skills even if I'm bad at them initially." },
            { id: "h3-q3", text: "I often hold back my words to avoid conflict." },
        ],
        aiPrompt: "Focus on communication, courage, and adaptability. Ask about their willingness to speak up, their learning style, and how they handle social risks.",
    },
    {
        id: "h4",
        icon: Home,
        type: "House",
        name: "4th House",
        title: "Emotional Foundations",
        description: "Tests your emotional security, comfort needs, and how your inner world shapes your outward behavior.",
        detailedDescription: "This house examines your emotional base, your need for comfort, and how deeply your past and family influence your present. It highlights attachment patterns, inner stability, and how you retreat or recharge. Strong expression signals deep emotional awareness; lower levels suggest detachment or unresolved roots.",
        questions: [
            { id: "h4-q1", text: "I need a lot of alone time to recharge emotionally." },
            { id: "h4-q2", text: "My childhood experiences heavily influence my current decisions." },
            { id: "h4-q3", text: "I feel safe expressing my vulnerability to close ones." },
        ],
        aiPrompt: "Focus on emotional roots, home life, and inner security. Ask about their relationship with their past, their need for privacy, and what makes them feel safe.",
    },
    {
        id: "h5",
        icon: Sparkles,
        type: "House",
        name: "5th House",
        title: "Creativity & Play",
        description: "Tests your creative expression, romantic spontaneity, and desire to be seen or appreciated.",
        detailedDescription: "This house captures your creative instincts, your sense of play, and how naturally you express joy or affection. It also touches on personal flair, originality, and emotional openness in love. High scores reflect vibrant creativity; lower ones indicate inhibition or self-doubt in expression.",
        questions: [
            { id: "h5-q1", text: "I prioritize fun and play in my daily life." },
            { id: "h5-q2", text: "I enjoy being the center of attention." },
            { id: "h5-q3", text: "I express my romantic feelings openly and spontaneously." },
        ],
        aiPrompt: "Focus on self-expression, romance, and creativity. Ask about their hobbies, their approach to love, and their need for validation.",
    },
    {
        id: "h6",
        icon: Activity,
        type: "House",
        name: "6th House",
        title: "Discipline & Mastery",
        description: "Tests your work ethic, consistency, habits, and how you handle pressure or everyday responsibilities.",
        detailedDescription: "This house explores your approach to routines, problem-solving, health discipline, and personal improvement. It measures how you navigate challenges, maintain structure, and take responsibility for your well-being. Strong scores point to resilience and order; weaker ones show avoidance or inconsistency.",
        questions: [
            { id: "h6-q1", text: "I thrive on routine and structure." },
            { id: "h6-q2", text: "I often feel overwhelmed by daily responsibilities." },
            { id: "h6-q3", text: "I am critical of myself when I am not productive." },
        ],
        aiPrompt: "Focus on daily routines, service, and health. Ask about their work habits, their attention to detail, and how they handle stress.",
    },
    {
        id: "h7",
        icon: Users,
        type: "House",
        name: "7th House",
        title: "Partnership & Bonding",
        description: "Tests your relationship style, intimacy needs, and how you show up in partnerships and close connections.",
        detailedDescription: "This house analyzes your patterns in romantic and platonic partnerships — your expectations, boundaries, and emotional reciprocity. It highlights how you balance closeness with independence, and how you respond to the needs of others. High scores show relational maturity; low ones show fear, imbalance, or overdependence.",
        questions: [
            { id: "h7-q1", text: "I often lose myself in relationships." },
            { id: "h7-q2", text: "I prefer making decisions together rather than alone." },
            { id: "h7-q3", text: "I struggle to maintain boundaries with close partners." },
        ],
        aiPrompt: "Focus on one-on-one relationships and partnerships. Ask about their dependency levels, their negotiation style, and what they seek in a partner.",
    },
    {
        id: "h8",
        icon: Eye,
        type: "House",
        name: "8th House",
        title: "Depth & Shadow",
        description: "Tests your comfort with vulnerability, hidden emotions, and transformative or intense experiences.",
        detailedDescription: "This house measures how you handle emotional depth, fear, trauma, intimacy, and the unknown. It reflects your willingness to confront difficult truths, your response to loss, and how you regenerate after setbacks. High scores show profound self-awareness; low ones indicate avoidance or emotional suppression.",
        questions: [
            { id: "h8-q1", text: "I am drawn to intense and transformative experiences." },
            { id: "h8-q2", text: "I hide my true feelings to protect myself." },
            { id: "h8-q3", text: "I am comfortable discussing taboo subjects." },
        ],
        aiPrompt: "Focus on transformation, shared resources, and the occult. Ask about their relationship with change, their secrets, and their depth of intimacy.",
    },
    {
        id: "h9",
        icon: Compass,
        type: "House",
        name: "9th House",
        title: "Belief & Exploration",
        description: "Tests your worldview, curiosity, openness to ideas, and inner search for meaning or purpose.",
        detailedDescription: "This house captures your relationship with belief systems, philosophy, and long-term personal growth. It measures your openness to new cultures, ideas, and life experiences. High scores show expansive thinking; lower ones imply rigidity or a narrowed worldview.",
        questions: [
            { id: "h9-q1", text: "I am constantly seeking a deeper meaning in life." },
            { id: "h9-q2", text: "I am open to changing my core beliefs when presented with new evidence." },
            { id: "h9-q3", text: "I feel restless when I stay in one place for too long." },
        ],
        aiPrompt: "Focus on philosophy, travel, and higher learning. Ask about their belief systems, their sense of adventure, and their quest for truth.",
    },
    {
        id: "h10",
        icon: Trophy,
        type: "House",
        name: "10th House",
        title: "Purpose & Achievement",
        description: "Tests ambition, responsibility, and how you define success and your public identity.",
        detailedDescription: "This house evaluates your drive for achievement, leadership tendencies, and how strongly you identify with your career or personal mission. It measures discipline, vision, and your response to external expectations. High scores signal purposeful ambition; low ones hint at uncertainty or disengagement.",
        questions: [
            { id: "h10-q1", text: "Social status and recognition are important to me." },
            { id: "h10-q2", text: "I feel a strong sense of responsibility towards my community." },
            { id: "h10-q3", text: "I am clear about my long-term career goals." },
        ],
        aiPrompt: "Focus on career, reputation, and authority. Ask about their professional goals, their relationship with public image, and their definition of success.",
    },
    {
        id: "h11",
        icon: Star,
        type: "House",
        name: "11th House",
        title: "Aspirations & Social Vision",
        description: "Tests your long-term goals, friendships, networking ability, and desire to contribute socially.",
        detailedDescription: "This house examines your connection to communities, your ability to collaborate, and your vision for the future. It reflects how your goals intertwine with collective growth. Strong scores show social alignment; lower ones show isolation or unclear aspirations.",
        questions: [
            { id: "h11-q1", text: "I value my friendships as much as my family." },
            { id: "h11-q2", text: "I enjoy connecting people with similar interests." },
            { id: "h11-q3", text: "I have a clear vision for how I want to contribute to society." },
        ],
        aiPrompt: "Focus on social networks, hopes, and wishes. Ask about their role in groups, their long-term dreams, and their humanitarian interests.",
    },
    {
        id: "h12",
        icon: Cloud,
        type: "House",
        name: "12th House",
        title: "Subconscious & Release",
        description: "Tests your inner fears, avoidance patterns, spiritual tendencies, and relationship with solitude.",
        detailedDescription: "This house explores your hidden emotions, self-sabotage loops, and instinct for withdrawal or transcendence. It measures how you navigate endings, surrender, and the unseen layers of your psyche. High scores show intuition and depth; low ones signal repression or escapism.",
        questions: [
            { id: "h12-q1", text: "I often feel misunderstood by others." },
            { id: "h12-q2", text: "I need solitude to process my emotions." },
            { id: "h12-q3", text: "I have vivid dreams or intuitive insights." },
        ],
        aiPrompt: "Focus on the subconscious, isolation, and spirituality. Ask about their dreams, their hidden fears, and their need for retreat.",
    },
];

export const grahas: CardData[] = [
    {
        id: "g1",
        icon: Sun,
        type: "Graha",
        name: "Sun",
        title: "Purpose & Ego Strength",
        description: "Tests your identity, pride, confidence, and inner drive to stand out or lead.",
        detailedDescription: "The Sun represents your core self: confidence, purpose, and the need to feel significant. It measures how strongly you assert your individuality, how you handle recognition, and where your leadership instincts come from. High scores show strong ego strength; lower scores point toward self-doubt or dimming your own light.",
        questions: [
            { id: "g1-q1", text: "I naturally take charge in group situations." },
            { id: "g1-q2", text: "I struggle with feeling invisible or unappreciated." },
            { id: "g1-q3", text: "My self-esteem is independent of others' opinions." },
        ],
        aiPrompt: "Focus on ego, leadership, and vitality. Ask about their need for recognition, their relationship with authority (inner and outer), and their core sense of purpose.",
    },
    {
        id: "g2",
        icon: Moon,
        type: "Graha",
        name: "Moon",
        title: "Emotion & Sensitivity",
        description: "Tests emotional regulation, intuition, and how you respond to changing moods or environments.",
        detailedDescription: "The Moon governs your inner emotional climate — how you process feelings, care for others, and seek comfort. It reflects sensitivity, adaptability, and instinctual responses. High scores indicate emotional richness; lower ones suggest rigidity, overthinking, or emotional disconnect.",
        questions: [
            { id: "g2-q1", text: "My mood changes frequently throughout the day." },
            { id: "g2-q2", text: "I am highly sensitive to the energy of my environment." },
            { id: "g2-q3", text: "I trust my gut feelings over logical analysis." },
        ],
        aiPrompt: "Focus on emotions, intuition, and nurturing. Ask about their emotional needs, their relationship with their mother/mother figure, and their comfort zone.",
    },
    {
        id: "g3",
        icon: Flame,
        type: "Graha",
        name: "Mars",
        title: "Drive & Conflict Response",
        description: "Tests willpower, assertiveness, anger patterns, and how you push through challenges.",
        detailedDescription: "Mars measures your action-taking energy: how you pursue goals, react to obstacles, and express aggression or passion. It shows how you stand your ground, confront problems, and channel intensity. High scores show boldness; lower ones suggest avoidance or passivity.",
        questions: [
            { id: "g3-q1", text: "I address conflicts directly and immediately." },
            { id: "g3-q2", text: "I often feel a build-up of unexpressed anger." },
            { id: "g3-q3", text: "I am energized by competition and challenges." },
        ],
        aiPrompt: "Focus on energy, action, and aggression. Ask about their conflict style, their drive to achieve, and how they handle anger.",
    },
    {
        id: "g4",
        icon: Brain,
        type: "Graha",
        name: "Mercury",
        title: "Thinking & Expression",
        description: "Tests clarity of thought, adaptability, communication patterns, and learning style.",
        detailedDescription: "Mercury represents your cognitive style: logic, reasoning, and how fluidly you communicate. It also reflects mental agility and curiosity. High scores show quick thinking and clarity; lower ones reveal confusion, rigidity, or difficulty expressing ideas.",
        questions: [
            { id: "g4-q1", text: "I overthink decisions before taking action." },
            { id: "g4-q2", text: "I can easily adapt my communication style to different people." },
            { id: "g4-q3", text: "I am always seeking new information and knowledge." },
        ],
        aiPrompt: "Focus on intellect, communication, and adaptability. Ask about their learning process, their communication style, and their decision-making.",
    },
    {
        id: "g5",
        icon: Sprout,
        type: "Graha",
        name: "Jupiter",
        title: "Growth & Wisdom",
        description: "Tests optimism, ethics, long-term thinking, and your desire for personal or spiritual expansion.",
        detailedDescription: "Jupiter measures your worldview — how hopeful, wise, and future-oriented you are. It gauges your moral compass, trust in life, and hunger for growth. High scores show expansive vision; lower ones suggest pessimism, fear, or narrow thinking.",
        questions: [
            { id: "g5-q1", text: "I believe that everything happens for a reason." },
            { id: "g5-q2", text: "I prioritize ethical considerations over personal gain." },
            { id: "g5-q3", text: "I am optimistic about the future." },
        ],
        aiPrompt: "Focus on wisdom, expansion, and optimism. Ask about their philosophy of life, their mentors, and their luck.",
    },
    {
        id: "g6",
        icon: Heart,
        type: "Graha",
        name: "Venus",
        title: "Love & Pleasure",
        description: "Tests desire for harmony, beauty, affection, and how you express or receive love.",
        detailedDescription: "Venus represents your relationship with pleasure, connection, aesthetics, and intimacy. It measures how you bond emotionally, what you find beautiful, and how you navigate attraction. High scores reflect warmth and sensuality; lower scores indicate detachment or difficulty giving/receiving affection.",
        questions: [
            { id: "g6-q1", text: "I need beauty and harmony in my surroundings to feel good." },
            { id: "g6-q2", text: "I express affection physically and verbally." },
            { id: "g6-q3", text: "I avoid conflict to maintain peace in relationships." },
        ],
        aiPrompt: "Focus on love, beauty, and harmony. Ask about their relationship values, their aesthetic sense, and what brings them pleasure.",
    },
    {
        id: "g7",
        icon: Hourglass,
        type: "Graha",
        name: "Saturn",
        title: "Discipline & Boundaries",
        description: "Tests patience, boundaries, fear patterns, and your relationship with hard work and limits.",
        detailedDescription: "Saturn tracks how you handle responsibility, structure, and long-term commitments. It also highlights fears, resilience, and your ability to endure discomfort. High scores show maturity and stability; lower scores show avoidance, impulsiveness, or fragility under pressure.",
        questions: [
            { id: "g7-q1", text: "I am willing to work hard for long-term rewards." },
            { id: "g7-q2", text: "I often feel restricted by rules and obligations." },
            { id: "g7-q3", text: "I have strict boundaries with my time and energy." },
        ],
        aiPrompt: "Focus on discipline, structure, and limitations. Ask about their relationship with authority, their fears, and their long-term goals.",
    },
    {
        id: "g8",
        icon: Zap,
        type: "Graha",
        name: "Rahu",
        title: "Ambition & Obsession",
        description: "Tests unconventional desires, ambition, risk-taking, and attraction to the unfamiliar or extreme.",
        detailedDescription: "Rahu represents your restless edges — the part of you that hungers for more, breaks norms, and pursues future possibilities. It captures your obsession patterns, innovation drive, and appetite for the unknown. High scores show bold exploration; low ones show fear of change or limited vision.",
        questions: [
            { id: "g8-q1", text: "I am often drawn to the unconventional or taboo." },
            { id: "g8-q2", text: "I have intense desires that can become obsessive." },
            { id: "g8-q3", text: "I am willing to take big risks to achieve my ambitions." },
        ],
        aiPrompt: "Focus on obsession, innovation, and the unconventional. Ask about their hidden desires, their rebellious side, and their relationship with technology/foreign things.",
    },
    {
        id: "g9",
        icon: Wind,
        type: "Graha",
        name: "Ketu",
        title: "Detachment & Intuition",
        description: "Tests spiritual instinct, letting-go ability, minimalism, and intuitive or subconscious insights.",
        detailedDescription: "Ketu embodies your inner detachment — the ability to release, observe, and rely on intuition instead of desire. It measures spiritual inclination, introspection, and neutrality. High scores indicate deep inner wisdom; lower scores show over-attachment, confusion, or difficulty letting go.",
        questions: [
            { id: "g9-q1", text: "I often feel detached from the material world." },
            { id: "g9-q2", text: "I rely on sudden insights rather than logical deduction." },
            { id: "g9-q3", text: "I find it easy to let go of possessions and attachments." },
        ],
        aiPrompt: "Focus on detachment, spirituality, and the past. Ask about their intuitive experiences, their ability to let go, and their spiritual practices.",
    },
];

export const allCards = [...houses, ...grahas];
