import { CardData } from "./types";

export const houses: CardData[] = [
    {
        id: "h1",
        type: "House",
        name: "1st House",
        title: "Self & Identity",
        description: "Tests how you see yourself, your confidence, and how you initiate actions in life.",
        questions: [
            { id: "h1-q1", text: "I often struggle to assert my true personality in new groups." },
            { id: "h1-q2", text: "I feel confident in my ability to start new projects alone." },
            { id: "h1-q3", text: "My physical appearance significantly impacts my self-worth." },
        ],
    },
    {
        id: "h2",
        type: "House",
        name: "2nd House",
        title: "Values & Security",
        description: "Tests your relationship with security, stability, money, and the core values that guide your choices.",
        questions: [
            { id: "h2-q1", text: "Financial stability is more important to me than taking risks." },
            { id: "h2-q2", text: "I often compromise my values to please others." },
            { id: "h2-q3", text: "I feel secure in my ability to provide for myself." },
        ],
    },
    {
        id: "h3",
        type: "House",
        name: "3rd House",
        title: "Expression & Courage",
        description: "Tests your communication style, social boldness, and willingness to try new or challenging experiences.",
        questions: [
            { id: "h3-q1", text: "I find it easy to express my controversial opinions." },
            { id: "h3-q2", text: "I enjoy learning new skills even if I'm bad at them initially." },
            { id: "h3-q3", text: "I often hold back my words to avoid conflict." },
        ],
    },
    {
        id: "h4",
        type: "House",
        name: "4th House",
        title: "Emotional Foundations",
        description: "Tests your emotional security, comfort needs, and how your inner world shapes your outward behavior.",
        questions: [
            { id: "h4-q1", text: "I need a lot of alone time to recharge emotionally." },
            { id: "h4-q2", text: "My childhood experiences heavily influence my current decisions." },
            { id: "h4-q3", text: "I feel safe expressing my vulnerability to close ones." },
        ],
    },
    {
        id: "h5",
        type: "House",
        name: "5th House",
        title: "Creativity & Play",
        description: "Tests your creative expression, romantic spontaneity, and desire to be seen or appreciated.",
        questions: [
            { id: "h5-q1", text: "I prioritize fun and play in my daily life." },
            { id: "h5-q2", text: "I enjoy being the center of attention." },
            { id: "h5-q3", text: "I express my romantic feelings openly and spontaneously." },
        ],
    },
    {
        id: "h6",
        type: "House",
        name: "6th House",
        title: "Discipline & Mastery",
        description: "Tests your work ethic, consistency, habits, and how you handle pressure or everyday responsibilities.",
        questions: [
            { id: "h6-q1", text: "I thrive on routine and structure." },
            { id: "h6-q2", text: "I often feel overwhelmed by daily responsibilities." },
            { id: "h6-q3", text: "I am critical of myself when I am not productive." },
        ],
    },
    {
        id: "h7",
        type: "House",
        name: "7th House",
        title: "Partnership & Bonding",
        description: "Tests your relationship style, intimacy needs, and how you show up in partnerships and close connections.",
        questions: [
            { id: "h7-q1", text: "I often lose myself in relationships." },
            { id: "h7-q2", text: "I prefer making decisions together rather than alone." },
            { id: "h7-q3", text: "I struggle to maintain boundaries with close partners." },
        ],
    },
    {
        id: "h8",
        type: "House",
        name: "8th House",
        title: "Depth & Shadow",
        description: "Tests your comfort with vulnerability, hidden emotions, and transformative or intense experiences.",
        questions: [
            { id: "h8-q1", text: "I am drawn to intense and transformative experiences." },
            { id: "h8-q2", text: "I hide my true feelings to protect myself." },
            { id: "h8-q3", text: "I am comfortable discussing taboo subjects." },
        ],
    },
    {
        id: "h9",
        type: "House",
        name: "9th House",
        title: "Belief & Exploration",
        description: "Tests your worldview, curiosity, openness to ideas, and inner search for meaning or purpose.",
        questions: [
            { id: "h9-q1", text: "I am constantly seeking a deeper meaning in life." },
            { id: "h9-q2", text: "I am open to changing my core beliefs when presented with new evidence." },
            { id: "h9-q3", text: "I feel restless when I stay in one place for too long." },
        ],
    },
    {
        id: "h10",
        type: "House",
        name: "10th House",
        title: "Purpose & Achievement",
        description: "Tests ambition, responsibility, and how you define success and your public identity.",
        questions: [
            { id: "h10-q1", text: "Social status and recognition are important to me." },
            { id: "h10-q2", text: "I feel a strong sense of responsibility towards my community." },
            { id: "h10-q3", text: "I am clear about my long-term career goals." },
        ],
    },
    {
        id: "h11",
        type: "House",
        name: "11th House",
        title: "Aspirations & Social Vision",
        description: "Tests your long-term goals, friendships, networking ability, and desire to contribute socially.",
        questions: [
            { id: "h11-q1", text: "I value my friendships as much as my family." },
            { id: "h11-q2", text: "I enjoy connecting people with similar interests." },
            { id: "h11-q3", text: "I have a clear vision for how I want to contribute to society." },
        ],
    },
    {
        id: "h12",
        type: "House",
        name: "12th House",
        title: "Subconscious & Release",
        description: "Tests your inner fears, avoidance patterns, spiritual tendencies, and relationship with solitude.",
        questions: [
            { id: "h12-q1", text: "I often feel misunderstood by others." },
            { id: "h12-q2", text: "I need solitude to process my emotions." },
            { id: "h12-q3", text: "I have vivid dreams or intuitive insights." },
        ],
    },
];

export const grahas: CardData[] = [
    {
        id: "g1",
        type: "Graha",
        name: "Sun",
        title: "Purpose & Ego Strength",
        description: "Tests your identity, pride, confidence, and inner drive to stand out or lead.",
        questions: [
            { id: "g1-q1", text: "I naturally take charge in group situations." },
            { id: "g1-q2", text: "I struggle with feeling invisible or unappreciated." },
            { id: "g1-q3", text: "My self-esteem is independent of others' opinions." },
        ],
    },
    {
        id: "g2",
        type: "Graha",
        name: "Moon",
        title: "Emotion & Sensitivity",
        description: "Tests emotional regulation, intuition, and how you respond to changing moods or environments.",
        questions: [
            { id: "g2-q1", text: "My mood changes frequently throughout the day." },
            { id: "g2-q2", text: "I am highly sensitive to the energy of my environment." },
            { id: "g2-q3", text: "I trust my gut feelings over logical analysis." },
        ],
    },
    {
        id: "g3",
        type: "Graha",
        name: "Mars",
        title: "Drive & Conflict Response",
        description: "Tests willpower, assertiveness, anger patterns, and how you push through challenges.",
        questions: [
            { id: "g3-q1", text: "I address conflicts directly and immediately." },
            { id: "g3-q2", text: "I often feel a build-up of unexpressed anger." },
            { id: "g3-q3", text: "I am energized by competition and challenges." },
        ],
    },
    {
        id: "g4",
        type: "Graha",
        name: "Mercury",
        title: "Thinking & Expression",
        description: "Tests clarity of thought, adaptability, communication patterns, and learning style.",
        questions: [
            { id: "g4-q1", text: "I overthink decisions before taking action." },
            { id: "g4-q2", text: "I can easily adapt my communication style to different people." },
            { id: "g4-q3", text: "I am always seeking new information and knowledge." },
        ],
    },
    {
        id: "g5",
        type: "Graha",
        name: "Jupiter",
        title: "Growth & Wisdom",
        description: "Tests optimism, ethics, long-term thinking, and your desire for personal or spiritual expansion.",
        questions: [
            { id: "g5-q1", text: "I believe that everything happens for a reason." },
            { id: "g5-q2", text: "I prioritize ethical considerations over personal gain." },
            { id: "g5-q3", text: "I am optimistic about the future." },
        ],
    },
    {
        id: "g6",
        type: "Graha",
        name: "Venus",
        title: "Love & Pleasure",
        description: "Tests desire for harmony, beauty, affection, and how you express or receive love.",
        questions: [
            { id: "g6-q1", text: "I need beauty and harmony in my surroundings to feel good." },
            { id: "g6-q2", text: "I express affection physically and verbally." },
            { id: "g6-q3", text: "I avoid conflict to maintain peace in relationships." },
        ],
    },
    {
        id: "g7",
        type: "Graha",
        name: "Saturn",
        title: "Discipline & Boundaries",
        description: "Tests patience, boundaries, fear patterns, and your relationship with hard work and limits.",
        questions: [
            { id: "g7-q1", text: "I am willing to work hard for long-term rewards." },
            { id: "g7-q2", text: "I often feel restricted by rules and obligations." },
            { id: "g7-q3", text: "I have strict boundaries with my time and energy." },
        ],
    },
    {
        id: "g8",
        type: "Graha",
        name: "Rahu",
        title: "Ambition & Obsession",
        description: "Tests unconventional desires, ambition, risk-taking, and attraction to the unfamiliar or extreme.",
        questions: [
            { id: "g8-q1", text: "I am often drawn to the unconventional or taboo." },
            { id: "g8-q2", text: "I have intense desires that can become obsessive." },
            { id: "g8-q3", text: "I am willing to take big risks to achieve my ambitions." },
        ],
    },
    {
        id: "g9",
        type: "Graha",
        name: "Ketu",
        title: "Detachment & Intuition",
        description: "Tests spiritual instinct, letting-go ability, minimalism, and intuitive or subconscious insights.",
        questions: [
            { id: "g9-q1", text: "I often feel detached from the material world." },
            { id: "g9-q2", text: "I rely on sudden insights rather than logical deduction." },
            { id: "g9-q3", text: "I find it easy to let go of possessions and attachments." },
        ],
    },
];

export const allCards = [...houses, ...grahas];
